package learn.avinash.drool.section08.step5

import learn.avinash.drool.domain.InvalidPassport;
import learn.avinash.drool.domain.Passport;
import learn.avinash.drool.domain.Validation;
import java.time.LocalDate;


rule "Everyone is at least 20"
	dialect "mvel"
	when
		forall ( Passport( age >= 20 ))
	then
		System.out.println( "Everyone whose passport is in session is at least 20 years old" );
end
