package learn.avinash.drool.section06.step1

import learn.avinash.drool.domain.Passport;
import learn.avinash.drool.domain.Validation;
import learn.avinash.drool.domain.VisaApplication;
import java.time.LocalDate
import learn.avinash.drool.domain.Visa;

rule "Issue visa for valid applications"
	dialect "mvel"
	when
	  $visaApplication: VisaApplication( validation == Validation.PASSED )
	then
	  Visa visa = new Visa( $visaApplication.getPassportNumber() );
	  System.out.println("Issue " + visa);
	  insert( visa )
end