package learn.avinash.drool.section06.step6

import learn.avinash.drool.domain.Validation;
import learn.avinash.drool.domain.Passport;
import java.time.LocalDate
import learn.avinash.drool.domain.Visa;
import learn.avinash.drool.domain.VisaApplication;

rule "Switch agenda to visa application validation"
	dialect "mvel"
	when
		not Passport( validation == Validation.UNKNOWN )
	then
		System.out.println( "There are no more passports without validation info" );
		drools.setFocus( "validate-application" );
end

rule "Switch agenda to visa issue"
	dialect "mvel"
	when
		not VisaApplication( validation == Validation.UNKNOWN )
	then
		System.out.println( "There are no more visa applications without validation info" );
		drools.setFocus( "issue-visa" );
end
