version: "3"

services:
  javaee8-service:
    build:
      context: .
    image: javaee8-service:1.0
    ports:
      - "8081:8080"
    depends_on:
      - message-queue
      - postgress-db
    networks:
      - jee8net
  message-queue:
    image: vromero/activemq-artemis:2.6.1
    environment:
      - ENABLE_JMX_EXPORTER=true
    expose:
      - "61616"
      - "1883"
      - "5672"
    ports:
      - "8161:8161"
    networks:
      - jee8net
  postgress-db:
    image: "postgres:9.6.3"
    environment:
      - POSTGRES_USER=javaee8
      - POSTGRES_PASSWORD=12qwasyx
    ports:
      - "5432:5432"
    networks:
      - jee8net
networks:
  jee8net:
    driver: bridge
