version: "3"

services:
  javaee8-service:
    build:
      context: .
    image: javaee8-service:1.0
    ports:
      - "8081:8080"
    networks:
      - jee8net

networks:
  jee8net:
    driver: bridge
