package learn.avinash.drool.section06.step5

import learn.avinash.drool.domain.Validation;
import learn.avinash.drool.domain.Passport;
import java.time.LocalDate
import learn.avinash.drool.domain.Visa;
import learn.avinash.drool.domain.VisaApplication;


rule "Report were visas"
	dialect "mvel"
	activation-group "conclusion"
	salience 20
	when
    Visa()
	then
	  System.out.println("Conclusion: at least one visa was issued");
end

rule "Report no visas"
	dialect "mvel"
	activation-group "conclusion"
	salience 10
	when
    VisaApplication( validation == Validation.FAILED )
	then
	  System.out.println("Conclusion: no visas were issued");
end
