package learn.avinash.drool.section06.step5

import learn.avinash.drool.domain.Validation;
import learn.avinash.drool.domain.Passport;
import java.time.LocalDate
import learn.avinash.drool.domain.Visa;
import learn.avinash.drool.domain.VisaApplication;

rule "Issue visa for valid applications"
	dialect "mvel"
	agenda-group "issue-visa"
	when
	  $visaApplication: VisaApplication( validation == Validation.PASSED )
	then
	  Visa visa = new Visa( $visaApplication.getPassportNumber() );
	  System.out.println("Issue " + visa);
	  insert( visa )
end
