package learn.avinash.drool.section08.step4
 
import learn.avinash.drool.domain.InvalidPassport;
import learn.avinash.drool.domain.Passport;
import learn.avinash.drool.domain.Validation;
import java.time.LocalDate;

rule "Expired passport"
	dialect "mvel"
	when
		$passport: Passport( isExpired()  )
	then
		System.out.println( $passport + " is INVALID because it is expired" );
		insert( new InvalidPassport($passport) )
end

rule "Full passport"
	dialect "mvel"
	when
		$passport: Passport( unusedVisaPages == 0   )
	then
		System.out.println( $passport + " is INVALID because it has no space for visa" );
		insert( new InvalidPassport($passport) )
end
