package learn.avinash.drool.section07.step4

import learn.avinash.drool.domain.InvalidPassport;
import learn.avinash.drool.domain.InvalidVisaApplication;
import learn.avinash.drool.domain.Passport;
import learn.avinash.drool.domain.Visa;
import learn.avinash.drool.domain.VisaApplication;

rule "Issue visa for valid applications"
	dialect "mvel"
	when
	  $visaApplication: VisaApplication( )
	  $passport: Passport( this.passportNumber == $visaApplication.passportNumber )
	  not InvalidPassport( this.passport == $passport )
	  not InvalidVisaApplication( this.visaApplication == $visaApplication )
	then
	  Visa visa = new Visa( $passport.getPassportNumber() );
	  System.out.println("Issue " + visa);
	  insertLogical( visa )
end
