package learn.avinash.drool.section07.step4

import learn.avinash.drool.domain.InvalidVisaApplication;
import learn.avinash.drool.domain.Passport;
import learn.avinash.drool.domain.Validation;
import learn.avinash.drool.domain.VisaApplication;

rule "Invalidate visa application where passport expires earlier than 6 months after visit end date"
  dialect "mvel"
  when
    $passport: Passport()
    $visaApplication: VisaApplication( passportNumber == $passport.passportNumber,
                       $passport.expiresOn.isBefore(visitEndDate.plusMonths(6)) )
  then
    System.out.println( "Set " + $visaApplication + " invalid as " + $passport + " is not valid 6 months after visit");
    insert( new InvalidVisaApplication($visaApplication) )
end
