server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AvinashTiwari/config
          username: qwe123kids@gmail.com
          password: P@ssw0rd12345
          search-paths: userservice, itemservice
        encrypt:
          enabled: false