spring:
  profiles:
    active: dev
camel.springboot.shutdownTimeout: 2

---

spring:
  profiles: mock

startRoute: direct:input
fromRoute : file:data/input?delete=true&readLock=none
toRoute1: mock:output

message: DEV Environment


---

spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url:  jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: postgres


startRoute: timer:hello?period=10s
fromRoute : file:data/input?delete=true&readLock=none
toRoute1: file:data/output
toRoute2: jdbc:dataSource

message: DEV Environment

---
spring:
  profiles: stage
  datasource:
    driver-class-name: org.postgresql.Driver
    url:  jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: postgres

startRoute: timer:hello?period=10s
fromRoute : file:data/input?delete=true&readLock=none
toRoute1: file:data/output
toRoute2: jdbc:dataSource

message: STAGE Environment

---
spring:
  profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url:  jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: postgres

startRoute: timer:hello?period=10s
fromRoute : file:data/input?delete=true&readLock=none
toRoute1: file:data/output
toRoute2: jdbc:dataSource


message: PROD Environment
---